# Use the official Node.js image as the base image
ARG VARIANT=18-alpine3.16
FROM node:${VARIANT}

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json (if available)
COPY package*.json .


# Install dependencies
RUN npm install 

# Copy the rest of your application code
COPY . .

# Build the application (if applicable)
RUN npm run build



# Set the command to start the application
CMD ["npm", "start"]
