version: '1'
services:
  api:
    build: 
      context: .  # Build from the current context
      dockerfile: ../server/Dockerfile.server
    container_name: backend_api
    ports: 
    - "8000:8000"
    volumes:
    - ../server:/app
    - node_modules:/app/node_modules
  client:
    build: 
      context: .  # Build from the current context
      dockerfile: ../Dockerfile.client
    container_name: taxigo_client
    ports:
      -3000:3000
    volumes:
      - ../:app
      - node_modules:/app/node_modules
    stdin_open: true
    tty: true

volumes:
  node_modules: {}